### ISSUE TITLE
use code coverage and code linting

### ISSUE THREAD

**Issue by schloerke** [rstudio-education/grader#15]
Add to `.travis.yml`
```yaml
r_binary_packages:
  - jimhester/lintr
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
```

Exec in `R`
```r
usethis::use_coverage("codecov")
usethis::use_build_ignore(".lintr")

lintr::lint_package() %>% 
  as.data.frame %>% 
  dplyr::group_by(linter) %>% 
  dplyr::tally(sort = TRUE) %$% 
  sprintf(
    "linters: with_defaults(\n    %s\n    NULL\n  )\n", 
    paste0(linter, " = NULL, # ", n, collapse = "\n    ")
  ) %>% 
  cat(file = ".lintr")
```

* Remove the packages from `Description`'s `Suggests`.
* Adjust the lint to allow for lines up to 100 characters.  (link: https://github.com/jimhester/lintr#project-configuration)

```r
lintr::lint_package(path = '.', relative_path = TRUE, with_defaults(line_length_linter(100)))
```
* Add the code coverage badge to the readme
